/* prettier-ignore */
export const data = [
[
    "IDENTITÀ", "lobular", true, 8,
    "La sagra è l'evento che", "baikal", false, 4,
    "presenta il vissuto", "baikal", false, 5,
    "nel mondo.", "basteleur", true, 6,
    " É l'occasione straordinaria", "baikal", false, 5,
     "di mostrare l'ordinario.", "baikal", false, 6,
],
[
    "simbolo", "identita",2/3,0,
     "La festa ", "ouroboros", true, 6,
    "è la celebrazione ", "baikal", false, 5,
    "nostalgica di ", "basteleur", true, 5,
     "un mondo perduto.", "basteleur", true, 5,
    "Le nuove reti sociali ", "ouroboros", false, 5,
    "ricercano visibilità adattandosi o", "baikal", true, 5,
    "reinventando forme di narrazione", "baikal", false, 5,
    "significativa.", "lobular", true, 8,
    "simbolo", "identita",1/3,1,
    ],
[
     "IDENTITÀ", "lobular", true, 8,
    "L'apparente", "ouroboros", false, 4,
    "stranezza", "baikal", false, 9,
    "degli elementi folkloristici ", "basteleur", false, 6,
    "primitivi ha come missione ", "baikal", true, 5,
     "primaria di illustrare ", "baikal", false, 6,
    "simbolo", "identita",1/3,0,
   "la Natura. ", "lobular", true, 6,
],
[
    "I riti, i fatti culturali ", "baikal", false, 4,
    "non sono mai relativi ", "basteleur", false, 5,
     "ad un particolare ", "ouroboros", true, 5,
  "simbolo", "identita",2/3,true,
    "oridne storico ", "ouroboros", false, 5,
        "ma solo alle grandi ", "baikal", true, 5,
    "forme neutre ", "baikal", false, 7,
       "dei luoghi comuni cosmici, ", "lobular", true, 4,
    "le stagioni, le calamità e ", "baikal", false, 5,
       "la morte.", "lobular", true, 8,
],
[
    "simbolo", "trasgressione",1/3,1,
    "titolo", "trasgressione", "", "",
    "La festa", "lobular", true, 8,
    "è la trasgressione", "baikal", false, 5,
    "ritualizzata dei tabù,", "basteleur", true, 3,
    "il rilascio", "baikal", false, 7,
     "di angoscia e", "lobular", false, 6,
     "disincanto sociale.", "ouroboros", true, 6,
],
[
    "Nella sagra", "baikal", false, 8,
    "la comunità esplora", "basteleur", true, 5,
     "i domini dell'escluso", "lobular", true, 4,
    "e del proibito.", "ouroboros", false, 5,
       "simbolo", "trasgressione",1/3,1,
    ],
[
    "titolo", "trasgressione", "", "",
    "simbolo", "trasgressione",1/3,1,
    "La diluizione", "baikal", true, 8,
    "politica di momenti", "basteleur", false, 5,
    "rivoluzionari,", "lobular", true, 5,
    "agisce come ", "baikal", false, 7,
     "valvola di sfogo", "lobular", false, 5,
     "e sicurezza.", "ouroboros", true, 6,
       "simbolo", "trasgressione",1/3,1,
    ],
      ["COMUNITÀ", "basteleur", true, 8,
    "L’esperienza della ", "ouroboros", false, 4,
      "simbolo", "comunita",1/5,2,
     "simbolo", "comunita",1/5,1,
     "simbolo", "comunita",1/5,0,
    "festa ", "baikal", true, 14,
    "avvolge tutti ", "basteleur", false, 6,
    "i soggetti agenti, ", "lobular", true, 5,
     "dal co-protagonosta", "baikal", false, 6,
     " allo spettatore puro. ", "ouroboros", true, 7,
      "simbolo", "comunita",1/2,1,
     ],
          [
    "simbolo", "comunita",1/4,1,
    "titolo", "comunita", "", "",
    "simbolo", "comunita",1/4,1,
    "I ruoli sociali ", "baikal", false, 8,
    "traditi ", "basteleur", true, 8,
    "nei giorni di festa", "lobular", true, 5,
    "tornano poi a ", "baikal", false, 7,
     "riaffermarsi ", "lobular", false, 5,
     "più forte.", "ouroboros", true, 6,
       "simbolo", "comunita",1/3,1,
    ],
        [
     "simbolo", "politica",1/6,1,
     "POLITICA", "lobular", true, 14,
    "Trasgredire", "baikal", false, 8,
    "le egemonie", "baikal", false, 7,
    "per cercare nuovi modi ", "basteleur", true, 6,
    "di comunità.", "baikal", false, 8,
    "simbolo", "politica",1/3,0,
    ],
   ["simbolo", "politica",1/5,1,
    "POLITICA", "baikal", true, 12,
    "Leader politici e", "ouroboros", false, 5,
  "intellettuali", "baikal", false, 8,
    "sono capaci di", "basteleur", false, 6,
     "orientare", "baikal", false, 8, 
"una storia", "baikal", false, 8,
"della festa.", "lobular", true, 8,
],
[
    "La manifestazione", "lobular", false, 4,
     "è una polifonia di voci", "baikal", false, 5,
     "in relazione", "ouroboros", true, 7,
   "di potere dentro ", "lobular", true, 5,
    "una cornice goliardica.", "baikal", true, 5,
],
[
    "Ridefinire", "baikal", true, 10,
    "e reinstaurare", "basteleur", true, 6,
    "i ruoli all'interno", "baikal", false, 6,
     "della comunità.", "lobular", false, 6,
      "simbolo", "politica",1/5,1,
     ],
        [
    "simbolo", "rito",1/3,1,
    "titolo", "rito", "", "",
    "La sagra ", "baikal", false, 8,
    "offre dei momenti", "basteleur", true, 5,
    "di stabilità ", "lobular", true, 5,
    "in un mondo ", "baikal", false, 7,
     "altamente mobile.", "lobular", false, 5,
],
[
     "Oggetti,", "ouroboros", true, 8,
    "cibo ed esperienze", "ouroboros", true, 7,
    "della sagra", "lobular", true, 5,
    "sono i rituali", "baikal", true, 6,
    "familiari", "lobular", true, 10,
    "per le comunità", "basteleur", true, 6,
    "che la sperimentano.", "baikal", false, 6,
       "simbolo", "rito",1/6,1,
    ],
        [
   "simbolo", "rito",1/3,0,
    "RITO", "lobular", true, 14,
    "Una festa", "ouroboros", false, 5,
    "che si fa", "baikal", false, 9,
    "secondo tradizione", "basteleur", false, 6,
    "chiede di essere presa", "baikal", false, 5,
     "sul serio", "baikal", true, 10,
   "per quello che dice,", "lobular", true, 4,
    "ovvero per il suo", "baikal", false, 6,
    "contenuto simbolico", "basteleur", false, 5,
     "ed espressivo", "ouroboros", true, 5,
 ],[
    "gli attori festivi", "baikal", true, 7,
     "decreteranno", "ouroboros", true, 5,
    "strati di significato", "baikal", false, 5,
     "più o meno", "lobular", false, 7,
    "profondi", "ouroboros", false, 8,
    "a misura della loro", "ouroboros", false, 7,
    "intrinsichezza", "lobular", true, 6,
    "con la festa stessa", "baikal", false, 4,
    "e con il fatto", "lobular", false, 6,
    "tradizionale", "basteleur", true, 6,
    "in genere.", "ouroboros", false, 8,
    "simbolo", "rito",1/3,2,
    ],
 [
    "simbolo", "turismo",1/3,1,      
    "titolo", "turismo", true, 8,            
    "Le sagre fermentano", "basteleur", false, 3,
    "COME ANTIDOTO", "lobular", true, 5,
    "alla globalizzazione.", "basteleur", false, 4, 

    "Storie che vengono", "baikal", false, 5,
    "RISCOPERTE", "lobular", true, 7,
    "REINVENTATE", "ouroboros", false, 7, 
    "O CREATE.", "basteleur", true, 7, 
  ],[

    "Il FUORI SEDE vive", "baikal", true, 3,
    "una diaspora nel tentativo", "baikal", false, 3,
    "DI RICONNETTERSI", "lobular", true, 6,
    "alla propria IDENTITÀ.", "basteleur", true, 6,
  ],[

    "Le sagre riversano", "baikal", false, 3,
    "nel mondo esterno", "baikal", true, 3,
    "LE PROPRIE IDENTITÀ", "ouroboros", false, 7,
    "ma possono essere", "basteleur", false, 4,
    "comprese", "baikal", true, 3,
    "solo prendendo", "baikal", false, 4,
    "in considerazione", "basteleur", true, 5,
    "LE ALTRE REALTÀ.", "lobular", true, 6,
 ],[

    "simbolo", "turismo",2/10,1, 
    "titolo", "turismo", false, 6,

    "Contengono mondi", "basteleur", false, 3,
    "e li riversano", "basteleur", true, 3,
    "nella realtà", "lobular", true, 5,
    "in cui cui devono considerare", "baikal", false, 4,
    "l'immaginario.", "ouroboros", true, 6,

 ],[
             
    "Il tradizionale momento", "basteleur", false, 3,
    "di celebrazione sociale", "lobular", true, 5,
    "sono stati assorbiti", "baikal", true, 3,
    "dall’immenso stock", "baikal", false, 3,
    "di prodotti", "baikal", false, 4,
    "che i turisti", "ouroboros", true, 6,     
    "desiderano.", "ouroboros", true, 6, 
               
 ],[
    "Le esperienze", "basteleur", true, 3,
    "di feste e tradizioni", "baikal", true, 3,
    "sono sempre più" , "basteleur", false, 4,
    "massicciamente" , "lobular", true, 6,
    "mediate dalla riproduzione" , "basteleur", false, 4,
    "audiovisiva" , "ouroboros", true, 5,
    "e dalla circolazione" , "basteleur", false, 4,
    "telematica" , "ouroboros", true, 5,
    "simbolo", "turismo",2/10,1,

    ]
]

window.data = data
