/* eslint-disable */
/* prettier-ignore */
export const data = [
  [
    "IDENTITÀ", "lobular", true, 8,
    "La sagra è l'evento che", "baikal", false, 4,
    "presenta il vissuto ", "baikal", false, 5,
    "nel mondo.", "basteleur", true, 6,
    " É l'occasione straordinaria ", "baikal", false, 5,
    "di mostrare l'ordinario. ", "baikal", false, 6,
    "simbolo", "identita",2/3,0,
    "La festa ", "ouroboros", true, 6,
    "è la celebrazione ", "baikal", false, 5,
    "nostalgica di ", "basteleur", true, 5,
    "un mondo perduto.", "basteleur", true, 5,
    "simbolo", "identita",1/3,0,
    "Le nuove reti sociali ", "ouroboros", false, 5,
    "ricercano visibilità adattandosi o ", "baikal", true, 5,
    "reinventando forme di narrazione ", "baikal", false, 5,
    "significativa.", "lobular", true, 8,
    ],
    [
    "IDENTITÀ", "lobular", true, 8,
    "La sagra è l'evento che", "baikal", false, 4,
    "presenta il vissuto ", "baikal", false, 5,
    "nel mondo.", "basteleur", true, 6,
    " É l'occasione straordinaria ", "baikal", false, 5,
    "di mostrare l'ordinario. ", "baikal", false, 6,
    "simbolo", "identita",2/3,0,
    "La festa ", "ouroboros", true, 6,
    "è la celebrazione ", "baikal", false, 5,
    "nostalgica di ", "basteleur", true, 5,
    "un mondo perduto.", "basteleur", true, 5,
    "simbolo", "identita",1/3,0,
    "Le nuove reti sociali ", "ouroboros", false, 5,
    "ricercano visibilità adattandosi o ", "baikal", true, 5,
    "reinventando forme di narrazione ", "baikal", false, 5,
    "significativa.", "lobular", true, 8,
    ],
    [
    "simbolo", "trasgressione",1/3,0,
    "titolo", "trasgressione", "", "",
    "La festa", "lobular", true, 8,
    "è la trasgressione", "baikal", false, 5,
    "ritualizzata dei tabù,", "basteleur", true, 3,
    "il rilascio", "baikal", false, 7,
    "di angoscia e", "lobular", false, 6,
    "disincanto sociale.", "ouroboros", true, 6,
    "Nella sagra", "baikal", false, 8,
    "la comunità esplora", "basteleur", true, 5,
    "i domini dell'escluso", "lobular", true, 4,
    
    "e del proibito.", "ouroboros", false, 5,
    "simbolo", "trasgressione",1/3,0,
    ],
    [
    "titolo", "trasgressione", "", "",
    "simbolo", "trasgressione",1/3,0,
    "La diluizione", "baikal", true, 8,
    "politica di momenti", "basteleur", false, 5,
    "rivoluzionari,", "lobular", true, 5,
    "agisce come ", "baikal", false, 7,
    "valvola di sfogo", "lobular", false, 5,
    "e sicurezza.", "ouroboros", true, 6,
    "simbolo", "trasgressione",1/3,0,
    ]
]

window.data = data
