/* eslint-disable */
/* prettier-ignore */

export const data = [
  [
    "IDENTITÀ", "lobular", true, 8,
    "La sagra è l'evento che", "baikal", false, 4,
    "presenta il vissuto ", "baikal", false, 5,
    "nel mondo.", "basteleur", true, 6,
    " É l'occasione straordinaria ", "baikal", false, 5,
     "di mostrare l'ordinario. ", "baikal", false, 6,
    "simbolo", "identita",2/3,0,
     "La festa ", "ouroboros", true, 6,
    "è la celebrazione ", "baikal", false, 5,
    "nostalgica di ", "basteleur", true, 5,
     "un mondo perduto.", "basteleur", true, 5,
     "simbolo", "identita",1/3,0,
    "Le nuove reti sociali ", "ouroboros", false, 5,
        "ricercano visibilità adattandosi o ", "baikal", true, 5,
    "reinventando forme di narrazione ", "baikal", false, 5,
       "significativa.", "lobular", true, 8,
  ],
[
    "IDENTITÀ", "lobular", true, 8,
    "La sagra è l'evento che", "baikal", false, 4,
    "presenta il vissuto ", "baikal", false, 5,
    "nel mondo.", "basteleur", true, 6,
    " É l'occasione straordinaria ", "baikal", false, 5,
     "di mostrare l'ordinario. ", "baikal", false, 6,
    "simbolo", "identita",2/3,0,
     "La festa ", "ouroboros", true, 6,
    "è la celebrazione ", "baikal", false, 5,
    "nostalgica di ", "basteleur", true, 5,
     "un mondo perduto.", "basteleur", true, 5,
     "simbolo", "identita",1/3,0,
    "Le nuove reti sociali ", "ouroboros", false, 5,
        "ricercano visibilità adattandosi o ", "baikal", true, 5,
    "reinventando forme di narrazione ", "baikal", false, 5,
       "significativa.", "lobular", true, 8,
    ],
[
    "simbolo", "trasgressione",1/3,0,
    "titolo", "trasgressione", "", "",
    "La festa", "lobular", true, 8,
    "è la trasgressione", "baikal", false, 5,
    "ritualizzata dei tabù,", "basteleur", true, 3,
    "il rilascio", "baikal", false, 7,
     "di angoscia e", "lobular", false, 6,
     "disincanto sociale.", "ouroboros", true, 6,
    "Nella sagra", "baikal", false, 8,
    "la comunità esplora", "basteleur", true, 5,
     "i domini dell'escluso", "lobular", true, 4,
    "e del proibito.", "ouroboros", false, 5,
       "simbolo", "trasgressione",1/3,0,
    ],
[
    "titolo", "trasgressione", "", "",
    "simbolo", "trasgressione",1/3,0,
    "La diluizione", "baikal", true, 8,
    "politica di momenti", "basteleur", false, 5,
    "rivoluzionari,", "lobular", true, 5,
    "agisce come ", "baikal", false, 7,
     "valvola di sfogo", "lobular", false, 5,
     "e sicurezza.", "ouroboros", true, 6,
       "simbolo", "trasgressione",1/3,0,
   ],
   ["COMUNITÀ", "basteleur", true, 8,
    "L’esperienza della ", "ouroboros", false, 4,
      "simbolo", "comunita",1/5,2,
     "simbolo", "comunita",1/5,1,
     "simbolo", "comunita",1/5,0,
    "festa ", "baikal", true, 14,
    "avvolge tutti ", "basteleur", false, 6,
    "i soggetti agenti, ", "lobular", true, 5,
     "dal co-protagonosta", "baikal", false, 6,
     " allo spettatore puro. ", "ouroboros", true, 7,
      "simbolo", "comunita",1/2,1],
       [
    "simbolo", "comunita",1/4,1,
    "titolo", "comunita", "", "",
    "simbolo", "comunita",1/4,1,
    "I ruoli sociali ", "baikal", false, 8,
    "traditi ", "basteleur", true, 8,
    "nei giorni di festa", "lobular", true, 5,
    "tornano poi a ", "baikal", false, 7,
     "riaffermarsi ", "lobular", false, 5,
     "più forte.", "ouroboros", true, 6,
       "simbolo", "comunita",1/3,1,
    ],
        [
     "simbolo", "politica",1/6,1,
     "POLITICA", "lobular", true, 14,
    "Trasgredire", "baikal", false, 8,
    "le egemonie", "baikal", false, 7,
    "per cercare nuovi modi ", "basteleur", true, 6,
    "di comunità.", "baikal", false, 8,
    "simbolo", "politica",1/3,0,
    ],
    ["simbolo", "politica",1/5,1,
    "POLITICA", "baikal", true, 12,
    "Leader politici e", "ouroboros", false, 5,
    "intellettuali ", "baikal", false, 8,
    "sono capaci di", "basteleur", false, 6,
     "orientare", "baikal", false, 8,
    "La manifestazione ", "lobular", false, 4,
     "è una polifonia di voci ", "baikal", false, 5,
     "in relazione ", "ouroboros", true, 7,   
     "di potere dentro ", "lobular", true, 5,
    "una cornice goliardica.", "baikal", true, 5,
    "Ridefinire", "baikal", true, 10,
    "e reinstaurare", "basteleur", true, 6,
    "i ruoli all'interno", "baikal", false, 6,
     "della comunità.", "lobular", false, 6,
      "simbolo", "politica",1/5,1,
     ],
        [
    "simbolo", "rito",1/3,1,
    "titolo", "rito", "", "",
    "La sagra ", "baikal", false, 8,
    "offre dei momenti", "basteleur", true, 5,
    "di stabilità ", "lobular", true, 5,
    "in un mondo ", "baikal", false, 7,
     "altamente mobile.", "lobular", false, 5,
     "Oggetti,", "ouroboros", true, 8,     "cibo ed esperienze", "ouroboros", true, 7, "della sagra", "lobular", true, 5,
    "sono i rituali", "baikal", true, 6,
    "familiari", "lobular", true, 10,
    "per le comunità", "basteleur", true, 6,
    "che la sperimentano.", "baikal", false, 6,
       "simbolo", "rito",1/6,1,
    ]
]

window.data = data
